apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-backend-config
                  key: REACT_APP_BACKEND_URL
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}