apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-to-backend
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-frontend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.servicePort }}
  policyTypes:
    - Ingress