apiVersion: v1
kind: Service
metadata:
  name: random-word-frontend
  namespace: random-word-app
spec:
  selector:
    app: random-word-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Exposes the service only within the cluster